services:
#  telegram-bot-api:
#    image: aiogram/telegram-bot-api:latest
#    environment:
#      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
#      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
#      TELEGRAM_LOCAL: "true"
#    volumes:
#      - telegram-bot-api-data:/var/lib/telegram-bot-api
#    ports:
#      - "8081:8081"

  postgres:
    image: postgres:16.9
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    image: redis/redis-stack
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command:
      - redis-server
      - --protected-mode no
      - --client-output-buffer-limit
      - "pubsub 64mb 32mb 120"
      - --maxmemory
      - 2gb
      - --maxmemory-policy
      - allkeys-lru
      - --loadmodule
      - /opt/redis-stack/lib/redisearch.so
      - --loadmodule
      - /opt/redis-stack/lib/rejson.so
      - --loadmodule
      - /opt/redis-stack/lib/redistimeseries.so
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s


volumes:
  # telegram-bot-api-data:
  postgres_data:
  redis_data: